In [1]:
# Import Python libraries
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
import os

In [2]:
masterDF = pd.read_excel('Clearwater_SiteInformation.xlsx')
masterDF.dropna(subset=['Longitude', 'Latitude'],inplace=True)
masterDF

,StationNo,SiteName,SiteType,Latitude,Longitude,GeologicUnit,Aquifer,Label
0,8104300,"Salado Ck at Salado, TX",SW,30.944300,-97.534100,--,--,1
1,304940097413300,"Salado Ck blw conf of N and S Salado Ck, Jarre...",SW,30.827800,-97.692500,--,--,2
2,304957097304301,Little D.,GW,30.832476,-97.511911,Edwards Group,Edwards,3
3,305150097334401,Eastland W.,GW,30.863793,-97.562271,Edwards Group,Edwards,4
4,305303097423601,Gault site,GW,30.884233,-97.709950,Edwards Group,Edwards,5
5,305310097420601,Salado Quarries,GW,30.886049,-97.701580,Edwards Group,Edwards,6
6,305400097380101,Micheaux,GW,30.900000,-97.633600,Travis Peak Formation,Trinity,7
7,305406097461001,Stillman Valley Monitor,GW,30.901700,-97.769400,Hensell Member,Trinity,8
8,305457097353601,FM2843,GW,30.915800,-97.593300,Edwards Group,Edwards,9
9,305509097310901,Capps,GW,30.919113,-97.519073,Edwards Group,Edwards,10
10,305517097343501,Owens,GW,30.921500,-97.576367,Edwards Group,Edwards,11
11,305541097361701,Peters,GW,30.928167,-97.604667,Edwards Group,Edwards,12
12,305552097322801,Bloomer Mfg.,GW,30.931034,-97.541087,Edwards Group,Edwards,13
13,305602097315201,Salado Cemetery,GW,30.933900,-97.531100,Edwards Group,Edwards,14
14,305624097321101,Stagecoach Inn Hilltop #2,GW,30.940000,-97.536400,Edwards Group,Edwards,15
15,305631097321601,"Stagecoach Inn - ""Cave"" well",GW,30.941900,-97.537800,Edwards Group,Edwards,16
16,305633097323401,Robertson servants quarters,GW,30.942500,-97.542800,Edwards Group,Edwards,17
17,305636097320801,Critchfield,SP,30.943300,-97.535600,Edwards Group,Edwards,18
18,305637097321201,Big Boiling,SP,30.943600,-97.536700,Edwards Group,Edwards,19
19,305638097321401,Little Boiling,SP,30.943900,-97.537200,Edwards Group,Edwards,20
20,305639097320601,Benedict,SP,30.944200,-97.535000,Edwards Group,Edwards,21
21,305640097320201,Anderson,SP,30.944400,-97.533900,Edwards Group,Edwards,22
22,305640097323001,Robertson 2B,SP,30.944400,-97.541700,Edwards Group,Edwards,23
23,305650097354801,Coppin,GW,30.947139,-97.596690,Edwards Group,Edwards,24
24,305700097322701,Salado ISD,GW,30.950095,-97.540834,Edwards Group,Edwards,25
25,305716097335601,Tenroc Ranch 2,GW,30.954562,-97.565495,Edwards Group,Edwards,26
26,305718097314401,Salado Water Supply Corporation #2,GW,30.955000,-97.528900,Edwards Group,Edwards,27
27,305723097334601,Tenroc Ranch 1,GW,30.956418,-97.562801,Edwards Group,Edwards,28
28,305759097305201,Bartlett,GW,30.966383,-97.514435,Edwards Group,Edwards,29
29,305827097284501,Thaler,GW,30.974083,-97.479167,Edwards Group,Edwards,30
30,305946097293901,Broeker Funeral Home,GW,30.995983,-97.494133,Edwards Group,Edwards,31
31,310053097285601,Goode Towing,GW,31.014651,-97.482150,Edwards Group,Edwards,32
32,310056097263601,Stowe,GW,31.015485,-97.443256,Edwards Group,Edwards,33
33,310129097274701,Gifford,GW,31.024655,-97.463033,Edwards Group,Edwards,34
34,310639097490401,CTC well,GW,31.110800,-97.817800,Glen Rose Formation,Trinity,35
35,310754097222401,City of Temple #2,GW,31.131700,-97.373300,Hosston Member,Trinity,36

In [5]:
masterDF['geometry'] = masterDF.apply(lambda xy: Point(xy['Longitude'],xy['Latitude']),axis=1)

NameError: name 'masterDF' is not defined

In [6]:
masterDF = masterDF[['geometry', 'StationNo', 'SiteName', 'SiteType', 'WellNo', 'GeologicUnit', 'Aquifer']]

NameError: name 'masterDF' is not defined

In [7]:
proj4 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
masterDF = gpd.GeoDataFrame(masterDF,geometry='geometry' ,crs=proj4)

NameError: name 'masterDF' is not defined

In [ ]:
masterDF.to_file(os.path.join('shapefile', 'ClearwaterSites.shp'))